# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_web_rich_object', '0004_auto_20161214_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrichobject',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='webrichobject',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
    ]
